version: "2.1"

services:

  ###############################################################
  #    Functions service
  ###############################################################

  hesse:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "1108"

  ###############################################################
  #    StateFun runtime
  ###############################################################

  statefun-manager:
    image: apache/flink-statefun:3.2.0-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      ROLE: master
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/hesse/module.yaml

  statefun-worker:
    image: apache/flink-statefun:3.2.0-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - statefun-manager
      - kafka
      - hesse
    links:
      - "statefun-manager:statefun-manager"
      - "kafka:kafka"
      - "hesse:hesse"
    environment:
      ROLE: worker
      MASTER_HOST: statefun-manager
    volumes:
      - ./module.yaml:/opt/statefun/modules/hesse/module.yaml

  ###############################################################
  #    Kafka for ingress and egress
  ###############################################################

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - "zookeeper:zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ###############################################################
  #    Simple Kafka JSON producer to simulate ingress events
  ###############################################################

  hesse-producer:
    image: ververica/statefun-playground-producer:latest
    depends_on:
      - kafka
      - statefun-worker
    links:
      - "kafka:kafka"
    environment:
      APP_PATH: /mnt/example.txt
      APP_KAFKA_HOST: kafka:9092
      APP_KAFKA_TOPIC: example-temporal-graph4
      APP_JSON_PATH: src_id
    volumes:
      - ./example.txt:/mnt/example.txt