version: '2.1'
services:
  hesse:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
    - '1108'
    depends_on:
    - hesse-benchmarks
  statefun-manager:
    image: apache/flink-statefun:3.2.0-java11
    expose:
    - '6123'
    ports:
    - 8081:8081
    environment:
      ROLE: master
      MASTER_HOST: statefun-manager
    volumes:
    - ./module.yaml:/opt/statefun/modules/hesse/module.yaml
    - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
  statefun-worker:
    image: apache/flink-statefun:3.2.0-java11
    expose:
    - '6121'
    - '6122'
    depends_on:
    - statefun-manager
    - kafka
    - hesse
    links:
    - statefun-manager:statefun-manager
    - kafka:kafka
    - hesse:hesse
    environment:
      ROLE: worker
      MASTER_HOST: statefun-manager
    volumes:
    - ./module.yaml:/opt/statefun/modules/hesse/module.yaml
    - ./flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
    ports:
    - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.4.3
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
    links:
    - zookeeper:zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  hesse-graph-producer:
    image: spycsh/graph-producer:latest
    depends_on:
    - kafka
    links:
    - kafka:kafka
    environment:
      APP_PATH: /mnt/datasets/graph/email_edges_undirected.txt
      APP_KAFKA_HOST: kafka:9092
      APP_KAFKA_TOPIC: temporal-graph
      APP_DELAY_SECONDS: 0
      APP_LOOP: 'false'
      APP_JSON_PATH: src_id
    volumes:
    - ./datasets/graph/email_edges_undirected.txt:/mnt/datasets/graph/email_edges_undirected.txt
  hesse-query-producer:
    image: spycsh/query-producer:latest
    depends_on:
    - kafka
    links:
    - kafka:kafka
    environment:
      APP_PATH: /mnt/datasets/query/query_cc_email.txt
      APP_KAFKA_HOST: kafka:9092
      APP_KAFKA_TOPIC: query
      APP_DELAY_SECONDS: 0
      APP_DELAY_START_SECONDS: '10'
      APP_LOOP: 'false'
      APP_JSON_PATH: query_id
    volumes:
    - ./datasets/query/query_cc_email.txt:/mnt/datasets/query/query_cc_email.txt
  hesse-benchmarks:
    image: spycsh/hesse-benchmarks:v2.0
    depends_on:
    - kafka
    links:
    - kafka:kafka
    environment:
      APP_KAFKA_HOST: kafka:9092
      APP_KAFKA_TOPICS: storage-time filter-time query-results
      APP_DUMP_INTERVAL: 5000
      APP_DUMP_END: 122092
    volumes:
    - ./benchmarks:/app/results
